<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cartographe de controverses — Phase A : assertions structurées (claim) et
 * désaccords détectés (controversy + table de liaison), plus le cycle de vie de
 * l'analyse sur tree_node (cf. docs/spec-controverses-lacunes.md §9).
 *
 * Index HNSW sur claim.embedding (regroupement flou des assertions par
 * « exposure → outcome ») + B-tree sur (exposure_norm, outcome_norm) pour le
 * GROUP BY exact. Suit le SQL pgvector des migrations existantes.
 */
final class Version20260623100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cartographe de controverses (Phase A) : tables claim, controversy + liaison, analysis_status sur tree_node.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');

        $this->addSql(<<<'SQL'
            CREATE TABLE claim (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                exposure_label VARCHAR(255) NOT NULL,
                outcome_label VARCHAR(255) NOT NULL,
                exposure_norm VARCHAR(255) NOT NULL,
                outcome_norm VARCHAR(255) NOT NULL,
                direction VARCHAR(16) NOT NULL,
                method VARCHAR(32) NOT NULL,
                confidence VARCHAR(16) NOT NULL,
                population VARCHAR(255) DEFAULT NULL,
                sample_size INT DEFAULT NULL,
                effect_size VARCHAR(255) DEFAULT NULL,
                stated_limitations TEXT DEFAULT NULL,
                future_work JSON NOT NULL,
                quote TEXT NOT NULL,
                embedding vector(384) DEFAULT NULL,
                extraction_model VARCHAR(128) NOT NULL,
                raw JSON DEFAULT NULL,
                extracted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                publication_id INT NOT NULL,
                tree_node_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_claim_publication ON claim (publication_id)');
        $this->addSql('CREATE INDEX idx_claim_tree_node ON claim (tree_node_id)');
        $this->addSql('CREATE INDEX idx_claim_axis ON claim (exposure_norm, outcome_norm)');
        $this->addSql('CREATE INDEX idx_claim_emb_hnsw ON claim USING hnsw (embedding vector_cosine_ops)');
        $this->addSql('ALTER TABLE claim ADD CONSTRAINT fk_claim_publication FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE claim ADD CONSTRAINT fk_claim_tree_node FOREIGN KEY (tree_node_id) REFERENCES tree_node (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql(<<<'SQL'
            CREATE TABLE controversy (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                exposure_norm VARCHAR(255) NOT NULL,
                outcome_norm VARCHAR(255) NOT NULL,
                consensus_score DOUBLE PRECISION NOT NULL,
                count_positive INT NOT NULL,
                count_negative INT NOT NULL,
                count_null INT NOT NULL,
                disagreement_axis VARCHAR(16) NOT NULL,
                summary TEXT DEFAULT NULL,
                status VARCHAR(16) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                tree_node_id INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_controversy_node ON controversy (tree_node_id)');
        $this->addSql('ALTER TABLE controversy ADD CONSTRAINT fk_controversy_tree_node FOREIGN KEY (tree_node_id) REFERENCES tree_node (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql(<<<'SQL'
            CREATE TABLE controversy_claim (
                controversy_id INT NOT NULL,
                claim_id INT NOT NULL,
                PRIMARY KEY (controversy_id, claim_id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_controversy_claim_controversy ON controversy_claim (controversy_id)');
        $this->addSql('CREATE INDEX idx_controversy_claim_claim ON controversy_claim (claim_id)');
        $this->addSql('ALTER TABLE controversy_claim ADD CONSTRAINT fk_cc_controversy FOREIGN KEY (controversy_id) REFERENCES controversy (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE controversy_claim ADD CONSTRAINT fk_cc_claim FOREIGN KEY (claim_id) REFERENCES claim (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("ALTER TABLE tree_node ADD analysis_status VARCHAR(16) DEFAULT 'not_analyzed' NOT NULL");
        $this->addSql('ALTER TABLE tree_node ADD analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE tree_node DROP analysis_status');
        $this->addSql('ALTER TABLE tree_node DROP analyzed_at');
        $this->addSql('ALTER TABLE controversy_claim DROP CONSTRAINT fk_cc_controversy');
        $this->addSql('ALTER TABLE controversy_claim DROP CONSTRAINT fk_cc_claim');
        $this->addSql('DROP TABLE controversy_claim');
        $this->addSql('ALTER TABLE controversy DROP CONSTRAINT fk_controversy_tree_node');
        $this->addSql('DROP TABLE controversy');
        $this->addSql('ALTER TABLE claim DROP CONSTRAINT fk_claim_publication');
        $this->addSql('ALTER TABLE claim DROP CONSTRAINT fk_claim_tree_node');
        $this->addSql('DROP TABLE claim');
    }
}
