<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614100158 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE author (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(512) NOT NULL, orcid VARCHAR(32) DEFAULT NULL, affiliation VARCHAR(512) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDAFD8C8A8077F40 ON author (orcid)');
        $this->addSql('CREATE INDEX idx_author_orcid ON author (orcid)');
        $this->addSql('CREATE TABLE authorship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT NOT NULL, publication_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_561C265238B217A7 ON authorship (publication_id)');
        $this->addSql('CREATE INDEX IDX_561C2652F675F31B ON authorship (author_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_authorship ON authorship (publication_id, author_id)');
        $this->addSql('CREATE TABLE ingestion_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, query JSON NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, processed INT NOT NULL, created INT NOT NULL, errors INT NOT NULL, status VARCHAR(16) NOT NULL, end_cursor VARCHAR(1024) DEFAULT NULL, log TEXT DEFAULT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BE1D5E5C953C1C61 ON ingestion_job (source_id)');
        $this->addSql('CREATE TABLE publication (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, doi VARCHAR(255) DEFAULT NULL, external_ids JSON NOT NULL, title TEXT NOT NULL, abstract TEXT DEFAULT NULL, publication_date DATE DEFAULT NULL, language VARCHAR(16) DEFAULT NULL, venue VARCHAR(512) DEFAULT NULL, type VARCHAR(64) DEFAULT NULL, license VARCHAR(128) DEFAULT NULL, oa_status VARCHAR(16) NOT NULL, oa_url TEXT DEFAULT NULL, fulltext_available BOOLEAN NOT NULL, fulltext_stored BOOLEAN NOT NULL, processing_status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AF3C67796694147A ON publication (doi)');
        $this->addSql('CREATE INDEX idx_publication_status ON publication (processing_status)');
        $this->addSql('CREATE TABLE publication_provenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_in_source VARCHAR(255) NOT NULL, observed_license VARCHAR(128) DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, publication_id INT NOT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF72986038B217A7 ON publication_provenance (publication_id)');
        $this->addSql('CREATE INDEX IDX_EF729860953C1C61 ON publication_provenance (source_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_provenance ON publication_provenance (publication_id, source_id)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, api_type VARCHAR(255) NOT NULL, default_license VARCHAR(128) DEFAULT NULL, active BOOLEAN NOT NULL, phase SMALLINT NOT NULL, config JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F7377153098 ON source (code)');
        $this->addSql('ALTER TABLE authorship ADD CONSTRAINT FK_561C265238B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE authorship ADD CONSTRAINT FK_561C2652F675F31B FOREIGN KEY (author_id) REFERENCES author (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ingestion_job ADD CONSTRAINT FK_BE1D5E5C953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE publication_provenance ADD CONSTRAINT FK_EF72986038B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE publication_provenance ADD CONSTRAINT FK_EF729860953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE authorship DROP CONSTRAINT FK_561C265238B217A7');
        $this->addSql('ALTER TABLE authorship DROP CONSTRAINT FK_561C2652F675F31B');
        $this->addSql('ALTER TABLE ingestion_job DROP CONSTRAINT FK_BE1D5E5C953C1C61');
        $this->addSql('ALTER TABLE publication_provenance DROP CONSTRAINT FK_EF72986038B217A7');
        $this->addSql('ALTER TABLE publication_provenance DROP CONSTRAINT FK_EF729860953C1C61');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE authorship');
        $this->addSql('DROP TABLE ingestion_job');
        $this->addSql('DROP TABLE publication');
        $this->addSql('DROP TABLE publication_provenance');
        $this->addSql('DROP TABLE source');
    }
}
