<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cartographe de controverses — Phase B : pistes inexplorées détectées
 * (chaînons manquants Swanson, cases creuses, lacunes auto-déclarées) avec les
 * champs de vérification croisée (§6.5). Cf. docs/spec-controverses-lacunes.md §9.
 */
final class Version20260623130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table research_gap (pistes inexplorées + champs de vérification croisée).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE research_gap (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                type VARCHAR(16) NOT NULL,
                concept_a VARCHAR(255) DEFAULT NULL,
                concept_b VARCHAR(255) DEFAULT NULL,
                concept_c VARCHAR(255) DEFAULT NULL,
                description TEXT NOT NULL,
                maturity_score DOUBLE PRECISION NOT NULL,
                rarity_score DOUBLE PRECISION NOT NULL,
                evidence_count INT NOT NULL,
                supporting_publication_ids JSON NOT NULL,
                status VARCHAR(16) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                verification VARCHAR(16) NOT NULL,
                expected_direction VARCHAR(16) DEFAULT NULL,
                observed_direction VARCHAR(16) DEFAULT NULL,
                corroborating_publication_ids JSON NOT NULL,
                contesting_publication_ids JSON NOT NULL,
                divergence_note TEXT DEFAULT NULL,
                verified_scope VARCHAR(32) DEFAULT NULL,
                verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                tree_node_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_research_gap_node ON research_gap (tree_node_id)');
        $this->addSql('ALTER TABLE research_gap ADD CONSTRAINT fk_research_gap_tree_node FOREIGN KEY (tree_node_id) REFERENCES tree_node (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE research_gap DROP CONSTRAINT fk_research_gap_tree_node');
        $this->addSql('DROP TABLE research_gap');
    }
}
