<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614135923 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, language VARCHAR(8) NOT NULL, validation_status VARCHAR(24) NOT NULL, type VARCHAR(16) NOT NULL, generated_by_ai BOOLEAN NOT NULL, academic_block_validated BOOLEAN NOT NULL, validated_by_committee_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, question_id INT NOT NULL, tree_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DADD4A251E27F6BF ON answer (question_id)');
        $this->addSql('CREATE INDEX IDX_DADD4A258C8A3DCA ON answer (tree_node_id)');
        $this->addSql('CREATE TABLE answer_revision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, academic_content TEXT NOT NULL, vulgarization_content TEXT NOT NULL, author_type VARCHAR(16) NOT NULL, change_summary VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, answer_id INT NOT NULL, parent_revision_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4A2914A9AA334807 ON answer_revision (answer_id)');
        $this->addSql('CREATE INDEX IDX_4A2914A976D66EFF ON answer_revision (parent_revision_id)');
        $this->addSql('CREATE TABLE footnote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, marker SMALLINT NOT NULL, doi VARCHAR(255) DEFAULT NULL, answer_revision_id INT NOT NULL, publication_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_155194D1DCF4ECAC ON footnote (answer_revision_id)');
        $this->addSql('CREATE INDEX IDX_155194D138B217A7 ON footnote (publication_id)');
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, embedding vector(384) DEFAULT NULL, origin VARCHAR(24) NOT NULL, ask_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tree_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6F7494E8C8A3DCA ON question (tree_node_id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A251E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A258C8A3DCA FOREIGN KEY (tree_node_id) REFERENCES tree_node (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answer_revision ADD CONSTRAINT FK_4A2914A9AA334807 FOREIGN KEY (answer_id) REFERENCES answer (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answer_revision ADD CONSTRAINT FK_4A2914A976D66EFF FOREIGN KEY (parent_revision_id) REFERENCES answer_revision (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE footnote ADD CONSTRAINT FK_155194D1DCF4ECAC FOREIGN KEY (answer_revision_id) REFERENCES answer_revision (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE footnote ADD CONSTRAINT FK_155194D138B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E8C8A3DCA FOREIGN KEY (tree_node_id) REFERENCES tree_node (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE publication ALTER embedding TYPE vector(384)');
        $this->addSql('ALTER TABLE tree_node ALTER embedding TYPE vector(384)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A251E27F6BF');
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A258C8A3DCA');
        $this->addSql('ALTER TABLE answer_revision DROP CONSTRAINT FK_4A2914A9AA334807');
        $this->addSql('ALTER TABLE answer_revision DROP CONSTRAINT FK_4A2914A976D66EFF');
        $this->addSql('ALTER TABLE footnote DROP CONSTRAINT FK_155194D1DCF4ECAC');
        $this->addSql('ALTER TABLE footnote DROP CONSTRAINT FK_155194D138B217A7');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494E8C8A3DCA');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE answer_revision');
        $this->addSql('DROP TABLE footnote');
        $this->addSql('DROP TABLE question');
        $this->addSql('ALTER TABLE publication ALTER embedding TYPE vector');
        $this->addSql('ALTER TABLE tree_node ALTER embedding TYPE vector');
    }
}
