<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614121344 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Lot 4 : extension pgvector, arbre des connaissances (DAG) et suggestions de placement.';
    }

    public function up(Schema $schema): void
    {
        // Extension pgvector requise par les colonnes vector(384).
        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');
        $this->addSql('CREATE TABLE placement_suggestion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score DOUBLE PRECISION NOT NULL, method VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, publication_id INT NOT NULL, tree_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90F7600538B217A7 ON placement_suggestion (publication_id)');
        $this->addSql('CREATE INDEX IDX_90F760058C8A3DCA ON placement_suggestion (tree_node_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_placement ON placement_suggestion (publication_id, tree_node_id)');
        $this->addSql('CREATE TABLE tree_edge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, principal BOOLEAN NOT NULL, parent_id INT NOT NULL, child_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CA85B951727ACA70 ON tree_edge (parent_id)');
        $this->addSql('CREATE INDEX IDX_CA85B951DD62C21B ON tree_edge (child_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tree_edge ON tree_edge (parent_id, child_id)');
        $this->addSql('CREATE TABLE tree_node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, label VARCHAR(512) NOT NULL, description TEXT DEFAULT NULL, domain VARCHAR(128) DEFAULT NULL, openalex_concept_id VARCHAR(64) DEFAULT NULL, level SMALLINT NOT NULL, embedding vector(384) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3AFC8272989D9B62 ON tree_node (slug)');
        $this->addSql('CREATE INDEX idx_tree_node_concept ON tree_node (openalex_concept_id)');
        $this->addSql('ALTER TABLE placement_suggestion ADD CONSTRAINT FK_90F7600538B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE placement_suggestion ADD CONSTRAINT FK_90F760058C8A3DCA FOREIGN KEY (tree_node_id) REFERENCES tree_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tree_edge ADD CONSTRAINT FK_CA85B951727ACA70 FOREIGN KEY (parent_id) REFERENCES tree_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tree_edge ADD CONSTRAINT FK_CA85B951DD62C21B FOREIGN KEY (child_id) REFERENCES tree_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE publication ADD embedding vector(384) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE placement_suggestion DROP CONSTRAINT FK_90F7600538B217A7');
        $this->addSql('ALTER TABLE placement_suggestion DROP CONSTRAINT FK_90F760058C8A3DCA');
        $this->addSql('ALTER TABLE tree_edge DROP CONSTRAINT FK_CA85B951727ACA70');
        $this->addSql('ALTER TABLE tree_edge DROP CONSTRAINT FK_CA85B951DD62C21B');
        $this->addSql('DROP TABLE placement_suggestion');
        $this->addSql('DROP TABLE tree_edge');
        $this->addSql('DROP TABLE tree_node');
        $this->addSql('ALTER TABLE publication DROP embedding');
    }
}
