<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614155630 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, real_name VARCHAR(255) NOT NULL, pseudo VARCHAR(120) DEFAULT NULL, profile_type VARCHAR(16) NOT NULL, identity_verified BOOLEAN NOT NULL, verification_method VARCHAR(32) DEFAULT NULL, orcid VARCHAR(32) DEFAULT NULL, affiliation VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, reputation INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON app_user (email)');
        $this->addSql('CREATE TABLE domain_expertise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, tree_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4EA0DC5A76ED395 ON domain_expertise (user_id)');
        $this->addSql('CREATE INDEX IDX_C4EA0DC58C8A3DCA ON domain_expertise (tree_node_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_expertise ON domain_expertise (user_id, tree_node_id)');
        $this->addSql('ALTER TABLE domain_expertise ADD CONSTRAINT FK_C4EA0DC5A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE domain_expertise ADD CONSTRAINT FK_C4EA0DC58C8A3DCA FOREIGN KEY (tree_node_id) REFERENCES tree_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE publication ALTER embedding TYPE vector(384)');
        $this->addSql('ALTER TABLE question ALTER embedding TYPE vector(384)');
        $this->addSql('ALTER TABLE tree_node ALTER embedding TYPE vector(384)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE domain_expertise DROP CONSTRAINT FK_C4EA0DC5A76ED395');
        $this->addSql('ALTER TABLE domain_expertise DROP CONSTRAINT FK_C4EA0DC58C8A3DCA');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE domain_expertise');
        $this->addSql('ALTER TABLE publication ALTER embedding TYPE vector');
        $this->addSql('ALTER TABLE question ALTER embedding TYPE vector');
        $this->addSql('ALTER TABLE tree_node ALTER embedding TYPE vector');
    }
}
