<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Détection de plagiat / doublons intra-corpus — Lot 1 (cf. docs/spec-plagiat.md).
 *
 * - chunk_fingerprint       : empreinte MinHash 1:1 d'un publication_chunk (table brute).
 * - chunk_fingerprint_band  : bandes LSH indexées (rappel des chunks co-bucketés).
 * - duplication_finding     : paire de publications au contenu recouvrant (entité).
 */
final class Version20260626120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Antiplagiat Lot 1 : empreintes MinHash/LSH des chunks + rapprochements (duplication_finding).';
    }

    public function up(Schema $schema): void
    {
        // Empreinte MinHash d'un fragment plein texte (1:1 avec publication_chunk).
        $this->addSql(<<<'SQL'
            CREATE TABLE chunk_fingerprint (
                id BIGSERIAL PRIMARY KEY,
                chunk_id BIGINT NOT NULL,
                publication_id INT NOT NULL,
                signature TEXT NOT NULL,
                shingle_count INT NOT NULL,
                CONSTRAINT uniq_fp_chunk UNIQUE (chunk_id),
                CONSTRAINT fk_fp_chunk FOREIGN KEY (chunk_id) REFERENCES publication_chunk (id) ON DELETE CASCADE,
                CONSTRAINT fk_fp_pub FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE
            )
            SQL);
        $this->addSql('CREATE INDEX idx_fp_publication ON chunk_fingerprint (publication_id)');

        // Bandes LSH : deux chunks partageant un (band_index, band_hash) sont candidats.
        $this->addSql(<<<'SQL'
            CREATE TABLE chunk_fingerprint_band (
                fingerprint_id BIGINT NOT NULL,
                band_index SMALLINT NOT NULL,
                band_hash INT NOT NULL,
                PRIMARY KEY (fingerprint_id, band_index),
                CONSTRAINT fk_band_fp FOREIGN KEY (fingerprint_id) REFERENCES chunk_fingerprint (id) ON DELETE CASCADE
            )
            SQL);
        $this->addSql('CREATE INDEX idx_fp_band ON chunk_fingerprint_band (band_index, band_hash)');

        // Rapprochement (source, cible) — non décisionnel, statut tranché par le comité.
        $this->addSql(<<<'SQL'
            CREATE TABLE duplication_finding (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                source_id INT NOT NULL,
                target_id INT NOT NULL,
                type VARCHAR(16) NOT NULL,
                overlap_ratio DOUBLE PRECISION NOT NULL,
                max_jaccard DOUBLE PRECISION NOT NULL,
                semantic_sim DOUBLE PRECISION NOT NULL,
                shares_author BOOLEAN NOT NULL,
                passages JSON NOT NULL,
                status VARCHAR(16) NOT NULL,
                detected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                reviewed_by_id INT DEFAULT NULL,
                PRIMARY KEY (id),
                CONSTRAINT uniq_pair UNIQUE (source_id, target_id),
                CONSTRAINT fk_finding_source FOREIGN KEY (source_id) REFERENCES publication (id) ON DELETE CASCADE,
                CONSTRAINT fk_finding_target FOREIGN KEY (target_id) REFERENCES publication (id) ON DELETE CASCADE,
                CONSTRAINT fk_finding_reviewer FOREIGN KEY (reviewed_by_id) REFERENCES app_user (id) ON DELETE SET NULL
            )
            SQL);
        $this->addSql('CREATE INDEX idx_finding_status ON duplication_finding (status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS chunk_fingerprint_band');
        $this->addSql('DROP TABLE IF EXISTS chunk_fingerprint');
        $this->addSql('DROP TABLE IF EXISTS duplication_finding');
    }
}
