<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Revues de littérature sauvegardées par les chercheurs.
 */
final class Version20260622230000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table literature_review : revues de littérature enregistrées (par utilisateur).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE literature_review (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            topic VARCHAR(300) NOT NULL,
            content_md TEXT NOT NULL,
            sources JSON NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_literature_review_user ON literature_review (user_id)');
        $this->addSql('ALTER TABLE literature_review ADD CONSTRAINT fk_literature_review_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE literature_review');
    }
}
