<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Votes « OK / Pas OK » pondérés sur les réponses (Q/R), ouverts à tous.
 */
final class Version20260622210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table answer_vote : votes OK/Pas OK pondérés (chercheur/comité) sur les réponses.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE answer_vote (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            answer_id INT NOT NULL,
            user_id INT DEFAULT NULL,
            voter_key VARCHAR(80) NOT NULL,
            value SMALLINT NOT NULL,
            weight SMALLINT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_answer_vote_answer ON answer_vote (answer_id)');
        $this->addSql('CREATE INDEX idx_answer_vote_user ON answer_vote (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_answer_voter ON answer_vote (answer_id, voter_key)');
        $this->addSql('ALTER TABLE answer_vote ADD CONSTRAINT fk_answer_vote_answer FOREIGN KEY (answer_id) REFERENCES answer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE answer_vote ADD CONSTRAINT fk_answer_vote_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE answer_vote');
    }
}
