<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Évaluation critique AXIS (études transversales) par publication : table
 * axis_appraisal. UNE évaluation par publication (FK unique) ; statut comité
 * (ReviewStatus) — rien d'affiché publiquement avant « confirmed ».
 * Cf. docs/spec-axis-articles.md.
 */
final class Version20260628110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'axis_appraisal (évaluation AXIS des études transversales, par publication).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE axis_appraisal (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                publication_id INT NOT NULL,
                tree_node_id INT DEFAULT NULL,
                applicability VARCHAR(16) NOT NULL,
                study_design VARCHAR(64) DEFAULT NULL,
                answers JSON NOT NULL,
                justifications JSON NOT NULL,
                favorable_count INT DEFAULT 0 NOT NULL,
                assessable_count INT DEFAULT 0 NOT NULL,
                reliability_band VARCHAR(16) DEFAULT NULL,
                source_scope VARCHAR(24) NOT NULL,
                summary TEXT DEFAULT NULL,
                appraisal_model VARCHAR(128) NOT NULL,
                status VARCHAR(16) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                reviewed_by_id INT DEFAULT NULL,
                PRIMARY KEY (id),
                CONSTRAINT fk_axis_publication FOREIGN KEY (publication_id)
                    REFERENCES publication (id) ON DELETE CASCADE,
                CONSTRAINT fk_axis_tree_node FOREIGN KEY (tree_node_id)
                    REFERENCES tree_node (id) ON DELETE SET NULL,
                CONSTRAINT fk_axis_reviewed_by FOREIGN KEY (reviewed_by_id)
                    REFERENCES app_user (id) ON DELETE SET NULL
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_axis_publication ON axis_appraisal (publication_id)');
        $this->addSql('CREATE INDEX idx_axis_status ON axis_appraisal (status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE axis_appraisal');
    }
}
