<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Propositions de roadmap (page /roadmap) : stockées pour gestion en back-office.
 */
final class Version20260623120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table roadmap_proposal (propositions de roadmap publiques).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE roadmap_proposal (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(120) DEFAULT NULL,
                email VARCHAR(180) DEFAULT NULL,
                message TEXT NOT NULL,
                status VARCHAR(16) DEFAULT 'new' NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_roadmap_proposal_status ON roadmap_proposal (status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE roadmap_proposal');
    }
}
