<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Inscriptions « tenez-moi au courant » (newsletter / liste d'attente) par cible.
 */
final class Version20260623140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table newsletter_signup (inscriptions par cible).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE newsletter_signup (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email VARCHAR(180) NOT NULL,
                name VARCHAR(120) DEFAULT NULL,
                audience VARCHAR(32) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_newsletter_audience ON newsletter_signup (audience)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE newsletter_signup');
    }
}
