parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Analyses\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Entity/'
